#!/bin/bash
#pathogen nerdtree syntastic vim-airline vim-fugitive

mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
cd ~/.vim/bundle/
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/scrooloose/nerdtree
git clone https://github.com/scrooloose/syntastic

cd -
ln -s $PWD/10-powerline-symbols.conf ~/.config/fontconfig/conf.d/

wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
xdg-open PowerlineSymbols.otf 

